# Generated by Django 5.1 on 2024-08-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_rename_desctipriont_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='parametr',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='posparametr',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Название'),
        ),
    ]
