# Generated by Django 5.1 on 2024-08-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_data',
        ),
    ]
