# Generated by Django 5.1 on 2024-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parament',
            field=models.ManyToManyField(blank=True, null=True, through='About.PosParametr', to='About.parametr', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
