# Generated by Django 5.1 on 2024-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_alter_product_parament_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='images/no_photo.png', null=True, upload_to='images/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
