# Generated by Django 5.1 on 2024-08-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название компании')),
                ('agent_lastname', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('agent_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество представителя')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон представителя')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_exists', models.BooleanField(default=False, verbose_name='Логическое удаление')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='is_exists',
            field=models.BooleanField(default=False, verbose_name='Логическое удаление'),
        ),
        migrations.CreateModel(
            name='PosSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supply', models.DateTimeField(auto_now_add=True, verbose_name='Дата поставки')),
                ('product', models.ManyToManyField(through='About.PosSupply', to='About.product', verbose_name='Товары')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='About.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.AddField(
            model_name='possupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='About.supply', verbose_name='Поставка'),
        ),
    ]
