# Generated by Django 5.0.6 on 2024-06-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('customer_lastname', models.CharField(max_length=255, verbose_name='Фамилия заказчика')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('customer_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество заказчика')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки')),
                ('delivery', models.CharField(choices=[('PK', 'Самовывоз'), ('CR', 'Курьер')], max_length=2, verbose_name='Способ доставки')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completion_data', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('agent_lastname', models.CharField(max_length=255, verbose_name='Фамилия представителя')),
                ('agent_name', models.CharField(max_length=255, verbose_name='Имя представителя')),
                ('agent_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество представителя')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон представителя')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_exists', models.BooleanField(default=False, verbose_name='Логическое удаление')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_lastname', models.CharField(max_length=255, verbose_name='Фамилия владельца')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Имя владельца')),
                ('owner_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество владельца')),
                ('location', models.CharField(max_length=255, verbose_name='Расположение')),
                ('type_post', models.CharField(choices=[('AL', 'Любой вид отправки'), ('AR', 'Отправка самолётом'), ('TR', 'Отправка поездом'), ('TK', 'Отправка грузовиком')], default='AL', max_length=2, verbose_name='Вид отправки')),
                ('opacity', models.PositiveIntegerField(default=10000, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='PosParametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.parametr', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('desctipriont', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_data', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(default='images/no_photo.png', upload_to='images/%Y/%m/%d', verbose_name='Картинка')),
                ('is_exists', models.BooleanField(default=False, verbose_name='Логическое удаление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.category', verbose_name='Категории')),
                ('parament', models.ManyToManyField(through='about.PosParametr', to='about.parametr', verbose_name='Характеристика')),
                ('tag', models.ManyToManyField(blank=True, to='about.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='PosSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставок',
            },
        ),
        migrations.AddField(
            model_name='posparametr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='about.PosOrder', to='about.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='anonim', max_length=255, verbose_name='NickName')),
                ('rating', models.PositiveIntegerField(verbose_name='Оценка')),
                ('commit', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/%d', verbose_name='Фотография')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_supply', models.DateTimeField(auto_now_add=True, verbose_name='Дата поставки')),
                ('product', models.ManyToManyField(through='about.PosSupply', to='about.product', verbose_name='Товары')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.AddField(
            model_name='possupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='about.supply', verbose_name='Поставка'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('single_position', models.FloatField(verbose_name='Вес одной позиции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Хранение позиции',
                'verbose_name_plural': 'Хранение позиций',
            },
        ),
    ]
