# Generated by Django 5.0.7 on 2024-07-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_posorder_count_alter_posorder_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possupply',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='possupply',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.supply', verbose_name='Поставка'),
        ),
    ]
