# Generated by Django 5.0.7 on 2024-08-04 08:35

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название поста')),
                ('description', models.TextField(max_length=255, verbose_name='Описание поста')),
                ('image', models.ImageField(blank=True, default='images/no_photo.png', null=True, upload_to='images/%Y/%m%d', verbose_name='Обложка поста')),
                ('post', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Пост')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='About.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
